// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.11
// source: geecache.proto

package geecachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GeeCache_Get_FullMethodName = "/geecachepb.GeeCache/Get"
)

// GeeCacheClient is the client API for GeeCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeeCacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type geeCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewGeeCacheClient(cc grpc.ClientConnInterface) GeeCacheClient {
	return &geeCacheClient{cc}
}

func (c *geeCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, GeeCache_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeeCacheServer is the server API for GeeCache service.
// All implementations must embed UnimplementedGeeCacheServer
// for forward compatibility
type GeeCacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedGeeCacheServer()
}

// UnimplementedGeeCacheServer must be embedded to have forward compatible implementations.
type UnimplementedGeeCacheServer struct {
}

func (UnimplementedGeeCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGeeCacheServer) mustEmbedUnimplementedGeeCacheServer() {}

// UnsafeGeeCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeeCacheServer will
// result in compilation errors.
type UnsafeGeeCacheServer interface {
	mustEmbedUnimplementedGeeCacheServer()
}

func RegisterGeeCacheServer(s grpc.ServiceRegistrar, srv GeeCacheServer) {
	s.RegisterService(&GeeCache_ServiceDesc, srv)
}

func _GeeCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeeCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeeCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeeCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeeCache_ServiceDesc is the grpc.ServiceDesc for GeeCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeeCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geecachepb.GeeCache",
	HandlerType: (*GeeCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GeeCache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geecache.proto",
}
